### ISSUE TITLE
Add a quick note on what the phasors mean?

### ISSUE THREAD

**Issue by Pomax** [nevosegal/fft-js#3]
Running `fft([1,2,3,4, 5,6,7,8])` gives a real array of the form:
```
[
  0: 36
​​  1: -4
​  ​2: -4
​​  3: -4
​​  4: -4
​​  5: -4
​​  6: -3.9999999999999996
​  ​7: -3.9999999999999987
]
```
But what do the indices mean? Which sine functions do they map to? (e.g. should the index be considered the number of knots, so that it's simply [0]=amplitude(sin(x)), [1]=amplitude(sin(2x)), etc?)

**Comment by nevosegal** [comment]
I'm surprised that a real input produces a real output. I will need to check the code why this is the case. The indices represent the bins of the frequency spectrum. So each index contains data about frequencies around `(index * 2 * pi) / N`.

**Comment by Pomax** [comment]
The full answer result has `imag` array `[​​0, ​​9.65685424949238, ​​4, ​​1.6568542494923797, ​​0, ​​-1.6568542494923806, ​​-4, ​​-9.65685424949238]` and `real` array `[36, -4, ​​-4, ​​-4, ​​-4, ​​-4, ​​-3.9999999999999996, ​​-3.9999999999999987]`.

I guess I was confused on how to turn that into "plottable" values so I can actually see the frequency response (e.g. drawing it onto a canvas). After some more Google and Stackoverflow, does that mean I'd want to be using this?:

```javascript
let R = result.real, I = result.image, N = R.length, Tau = 2 * Math.PI, table = [];
for (let i = 0; i < N; i++) {
  let frequency = i * N / Tau;
  let amplitude = (R[i] ** 2 + I[i] ** 2) ** 0.5;
  table.push({ frequency, amplitude });
}
console.table(table);
```

If I run that, I get the following:

| (index) | frequency | amplitude |
|-|-|-|
| 0 | 0 | 36 |
| 1 |1.2732395447351628 | 10.452503719011013 |
| 2 | 2.5464790894703255 | 5.656854249492381 |
| 3 | 3.819718634205488 | 4.329568801169575 |
| 4 | 5.092958178940651 | 4 |
| 5 | 6.366197723675814 | 4.329568801169576 |
| 6 | 7.639437268410976 | 5.65685424949238 |
| 7 | 8.91267681314614 | 10.45250371901101 |

But is that correct? Do I need to manually normalize the results first? Also it seems unlikely that something would have a frequency of 0 Hz =)

(I'm trying to visualise both wave form and spectrum for .mp3 files over on https://noon-continuous-blackcurrant.glitch.me/ and the first is super simple, but the latter seems to not be right. Rather than the real spectrum that tools like RX show, I'm getting oddly vertically symmetrical results)

**Comment by nevosegal** [comment]
The formula you posted is correct apart from the frequency calculation. To get the frequency (in radians) of each bin you should use `let frequency = Tau * i / N`. 

The formula calculates the amplitude spectrum where amplitudes are represented linearly - you can also convert it to dB by calculating `20 * log10(f)` for each amplitude value. You can safely plot this, either the linear version of the decibel one.

**Comment by Pomax** [comment]
ahhhhhh hurray for numerating by the divisor... thanks!

**Comment by nevosegal** [comment]
No problem. Sorry for the delayed response 😀
